workspace: true

stages:
- install
- deploy

jobs:
- name: bundle_install
  stage: install
  image: sunci/capistrano:ruby-2.5.1
  script:
  - bundle _2.1.4_ install

- name: deploy:staging
  stage: deploy
  image: sunci/capistrano:ruby-2.5.1
  before_script:
  - pwd
  - ls -la
  - ls -la vendor/bundle
  - bundle _2.1.4_
  script:
  - bundle _2.1.4_ exec cap staging deploy
  only:
    branches:
    - master
