stages:
- deploy

jobs:
- name: deploy:staging
  stage: deploy
  image: sunci/ruby:2.5.1
  script:
  - bundle _2.1.4_ install --path vendor/bundle
  - bundle _2.1.4_ exec cap staging deploy
  cache:
  - key: vendor_$CI_BRANCH
    paths:
    - vendor/bundle
  only:
    branches:
    - master
  except:
    events:
    - pull_request
