workspace: true

stages:
- install
- deploy

jobs:
- name: bundle_install
  stage: install
  image: sunci/ruby:2.5.1
  script:
  - bundle _2.1.4_ install --path vendor/bundle
  - bundle _2.1.4_ exec cap -V
  - ls -la /usr/local/bundle/bin
  - echo $PATH
  cache:
  - key: vendor_$CI_BRANCH
    paths:
    - vendor/bundle

- name: deploy:staging
  stage: deploy
  image: sunci/ruby:2.5.1
  before_script:
  - pwd
  - ls -la /usr/local/bundle/bin
  script:
  - bundle _2.1.4_ --path vendor/bundle exec cap -V
  only:
    branches:
    - master
